### ISSUE TITLE
[question] Draw boundaries of program units

### ISSUE THREAD

**Issue by dodikk** [PaulTaykalo/objc-dependency-visualizer#31] opened 2016-04-07 08:12 UTC
Is there any way to mark the class circles as belonging to a certain library? 
It would be nice to have a rectangle around the group of classes from the same unit. Or, at least, mark them with the same colour.

The distinction may be done by either

1.  **prefix** (NS/AF/etc.)  - for cocoapods based repositories
2.  **target**  - for static lib/sub-project based repositories

**Comment by PaulTaykalo** [comment] 2016-04-07 08:46
duplicate of #13

**Closed by PaulTaykalo** 2016-04-07 08:46 UTC
Labels: duplicate

**Comment by dodikk** [comment] 2016-04-07 09:17
In #27 you've added a possibility to manage visualization targets manually using `-t` argument. For example, `-t "JFFAsyncOperations"`
I guess, at that point there is some information like `*.obj file X belongs to the target Y` that can be used as "unit boundaries".

Likewise, the option `-e "NS|UI|CA|KW|CF|RAC"` might be used not just for filtration. The prefixes might be used to detect libraries since the libraries are expected to have different prefixes (according to Apple's recommendations).

**Comment by dodikk** [comment] 2016-04-07 09:18
This idea is slightly different from the one described in #13 
However, they do have much in common.
